package com.xworkz.fest.work;

class Heat extends IronBox {
    Heat() {
        super();
        System.out.println("Heat class");
    }

    public void generatedByIronBox() {
        System.out.println("Heat is generated by the IronBox when turned on.");
    }

    public void helpsRemoveWrinkles() {
        System.out.println("Heat helps in removing wrinkles from clothes.");
    }

    public void variesWithTemperatureSetting() {
        System.out.println("Heat intensity varies with temperature settings.");
    }

    public void transfersThroughMetalPlate() {
        System.out.println("Heat is transferred through the metal plate of the IronBox.");
    }

    public void requiredForEfficientIroning() {
        System.out.println("Proper heat is required for efficient ironing.");
    }
}
